# 1D array

In [24]:
import colorama
from colorama import Fore
import numpy as np 
a = np.array([1,2,3])
print("1D array", a)

1D array [1 2 3]


# 2D array

In [25]:
b = np.array([[1,2,3,4,5],[1,9911,21,4121,1]])
b

array([[   1,    2,    3,    4,    5],
       [   1, 9911,   21, 4121,    1]])

In [26]:
var = np.array(10,dtype=np.int32)
var

array(10, dtype=int32)

# arange

In [27]:
p =np.arange(10)
p
# prints the range from 0 to n(given number in the function arange)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

# Empty

In [28]:
a1 = np.empty(5)
a1
# creates a array with random numbers and these numbers depends on the state of the memory 

array([ 1.  ,  2.75,  6.  , 10.75, 17.  ])

# Reshaping and shape functions of numpy

In [29]:
print(b.reshape(5,2)," 5 colomns and 2 rows")
print("-----------------------------------------------------")
# reshaped the 2D array in 5 colomns and 2 rows 
print(b.reshape(2,5), " 2 colomns and 5 rows")

[[   1    2]
 [   3    4]
 [   5    1]
 [9911   21]
 [4121    1]]  5 colomns and 2 rows
-----------------------------------------------------
[[   1    2    3    4    5]
 [   1 9911   21 4121    1]]  2 colomns and 5 rows


In [38]:
print(b.shape)
print(a.shape,"This won't print any rows as it is a 1D array and 1D array only have 1 row")
print(Fore.YELLOW + str(a.shape) )

(2, 5)
(3,) This won't print any rows as it is a 1D array and 1D array only have 1 row
(3,)


# Slicing 

In [56]:
print(b)
print(b[1:4])

print(np.vstack(b))
print(np.hstack(b))

[[   1    2    3    4    5]
 [   1 9911   21 4121    1]]
[[   1 9911   21 4121    1]]
[[   1    2    3    4    5]
 [   1 9911   21 4121    1]]
[   1    2    3    4    5    1 9911   21 4121    1]


In [62]:
Ar = np.arange(28)
print(Ar)
np.max(Ar)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27]


27

In [69]:
# Reverse the string
St = "Welcome to LPU"
print(St[::-1])

UPL ot emocleW


In [84]:
def reverse(s):
    str = ""
    for i in s:
        str = i + s
    return str
reverse(St)

'UWelcome to LPU'